### ISSUE TITLE
Review of MapActivity 0109

### ISSUE THREAD

**Issue by arsyee** [udacity-hungary/Dummy-Repository#2]
Some quick notes, as this is my first review, so I don't want anyone to misunderstand what I'm writing:
* I will comment on small things, too. That is nothing personal, I simply list ALL my observations, not just the small ones.
* My comments are not representing the one and only truth: maybe I am wrong, maybe we think differently, that is completely OK. If you fully agree, please change the code. If not, I'm happy to have a conversation and to discuss your opinions on why do you think differently.
* I understand that this is just an intermediate step, so probably you planned to change some of the below behaviour anyway. But feature is on the develop branch now, so it doesn't hurt to share my opinion :-)

So, in general the code looks good, I have only a few comments:

Comments/TODOs/everything shall be written in English (at least when they go to Github). This doesn't apply to the test data in DummyRepository.java, that is OK.

DummyRepository.java:
* Between the imports and the package name, one empty line is enough (i.e. pls delete line 3).
https://google.github.io/styleguide/javaguide.html#s4.6.1-vertical-whitespace see last comment.

DonationPoint.java:
Object state shall always be consistent. I'm not completely happy with the current approach of empty constructor and setting the fields with setters. It leaves the use of the class with the possibility of not completely set up the object.
I would create a single constructor, which takes all fields as parameters.
Furthermore, I see no point to have this class mutable, so please consider setting all fields as final and remove all constructors. Or do you see any use-case where such an object will change after construction?

MapActivity.java
It was a bit confusing that you have both a donationPoint and the list donationPoints as fields. First I thought there are mutually exclusive, but then came the onMarkerClick function, which sets donactionPoint from ther marker, and it got more confusing.
I have two improvement ideas here:
 * rename donationPoint to selectedDonationPoint, or
 * even if you have a single point, store it in the list; instead of having a separate reference to the selected point, you could just store the index from the list - this way you don't have to implement separately placing the list or the single point, you can just place the list, which sometimes contains only a single element (you can set a tag on the marker to refer to the index in the list - this way you don't have to reconstruct donationPoint from the Marker properties)

I'm a bit uncomfortable with the 3 setMarker(s) methods anyway. With the above
Are you sure the hardcoded CAMERA_ZOOM_LEVEL of 15 will always be OK? Also I didn't test the single point behavior (sorry for that), but it would be great to see what the difference. Somehow I hope that this part can be simplified.
The name of these methods are also a bit strange, because if a name starts with set, I would expect a setter, while these methods are actually adding markers to the map. But maybe this is just me.

Also, is it possible to programatically hide the FAB when no donationPoint is selected?

And the last comment: two lint warnings:
 * line 44: I don't care at the moment, I know you have plans with that variable :-)
 * line 170: sometimes I disagree with similar lint warnings, but actually in this case I would just modify the code (I mean if you keep setMarker as is now)
For a counter-example see BaseActivity line 64: actually I'm happy that Csaba suppressed that warning instead of modifying the code :-)

OK, this was long. But again, don't get discouraged! Actually after seeing the code I checked your experience on the Wiki, and I was very surprised, because the code you're writing looks very professional. I wouldn't have written a better code myself (really - it's a different art to review than to actually write it). So keep up the good work!

**Comment by vokod** [comment]
Ok, I mostly agree with the suggestions in the review, thanks for taking the time. Will work on implementing them.

**Comment by arsyee** [comment]
Well, thanks for doing the implementation. You were the first to deliver an actual feature, it's always hard to be on the spotlight :-)

**Comment by vokod** [comment]
> Comments/TODOs/everything shall be written in English (at least when they go to Github). This doesn't apply to the test data in DummyRepository.java, that is OK.

OK


> DummyRepository.java:
> 
> Between the imports and the package name, one empty line is enough (i.e. pls delete line 3).
> https://google.github.io/styleguide/javaguide.html#s4.6.1-vertical-whitespace see last comment.
> 
OK
Although I don't think this class will survive until the release, will it? 😄 

> DonationPoint.java:
> Object state shall always be consistent. I'm not completely happy with the current approach of empty constructor and setting the fields with setters. It leaves the use of the class with the possibility of not completely set up the object.
> I would create a single constructor, which takes all fields as parameters.
> Furthermore, I see no point to have this class mutable, so please consider setting all fields as final and remove all constructors. Or do you see any use-case where such an object will change after construction?

Totally agree

> 
> MapActivity.java
> It was a bit confusing that you have both a donationPoint and the list donationPoints as fields. First I thought there are mutually exclusive, but then came the onMarkerClick function, which sets donactionPoint from ther marker, and it got more confusing.
> I have two improvement ideas here:
> 
> rename donationPoint to selectedDonationPoint, or
> even if you have a single point, store it in the list; instead of having a separate reference to the selected point, you could just store the index from the list - this way you don't have to implement separately placing the list or the single point, you can just place the list, which sometimes contains only a single element (you can set a tag on the marker to refer to the index in the list - this way you don't have to reconstruct donationPoint from the Marker properties)

What a good idea!

> I'm a bit uncomfortable with the 3 setMarker(s) methods anyway. With the above

Ok, will do something about them

> Are you sure the hardcoded CAMERA_ZOOM_LEVEL of 15 will always be OK? Also I didn't test the single point behavior (sorry for that), but it would be great to see what the difference. Somehow I hope that this part can be simplified.

CAMERA_ZOOM_LEVEL of 15 is a good middleground for starting. Between city level and street level. But in the next push, the Activity will save its map's bounds.

> The name of these methods are also a bit strange, because if a name starts with set, I would expect a setter, while these methods are actually adding markers to the map. But maybe this is just me.

OK

> Also, is it possible to programatically hide the FAB when no donationPoint is selected?

Like the idea

And the last comment: two lint warnings:

> line 44: I don't care at the moment, I know you have plans with that variable :-)
> line 170: sometimes I disagree with similar lint warnings, but actually in this case I would just modify the code (I mean if you keep setMarker as is now)
> For a counter-example see BaseActivity line 64: actually I'm happy that Csaba suppressed that warning instead of modifying the code :-)

Line 44: yes, will be used.
Line 170: refactored.


> OK, this was long. But again, don't get discouraged! Actually after seeing the code I checked your experience on the Wiki, and I was very surprised, because the code you're writing looks very professional. I wouldn't have written a better code myself (really - it's a different art to review than to actually write it). So keep up the good work!

Yes, this was long, but this was my first ever code review and I didn't get burned 😄 
Thanks again for the thorough review!
Prepare for my next pull request soon 😉

**Comment by arsyee** [comment]
CAMERA_ZOOM_LEVEL (oh I hate typing constants from phone): 

I thought the plan was to show all points on the map, ie to dynamically set zoom level to cover everything

**Comment by vokod** [comment]
CAMERA_ZOOM_LEVEL is only set on single point mode, ie when the user get to the Activity by clicking an item from the main screen activity. 
When we show all points on the map (by choosing "Összes véradóhely" from the drawer menu) the camera position and zoom is computed by a LatLngBounds.Builder, which get every marker's position.

**Comment by arsyee** [comment]
Fair enough.

**Comment by arsyee** [comment]
https://plus.google.com/+PhilippeBreault/posts/7bnmwaZWfZy
